### ISSUE TITLE
Legal Advice Offer

### ISSUE THREAD

**Issue by inigma2** [KSP-SpaceDock/SpaceDock-Project#25]
from: http://forum.kerbalspaceprogram.com/index.php?/topic/132186-spacedock-dev-thread-the-kerbalstuff-replacement-site-now-live/&page=15#comment-2421176

One and all, I'd like to contribute to this effort.  I have no technical expertise, but I do have LEGAL expertise, as I am graduating law school in 85 days (wow!) and my school has free student-clinic representation for non-profit corporate clients.  I am based in New York, USA, but I can access other jurisdictions either within or potentially outside of the United States through my own personal network of lawyers, law students, and other professionals.

KerbalStuff failed, ultimately, because of a poor incentive-model (cost of time and money) to update and maintain it.

SpaceDock, or any successor, will eventually run into the same problem in some form.  Squad's licensing, of course, is with Curse.  Curse predicates its own commitment to Squad based on an economic model of forcing mod downloaders to physically visit their website and be exposed to banner ads as their primary method of cost defrayment and profit generation.  This is reasonable, because mod cloud-storage is not free; mod hosting and listing and indexing is not free; and bandwidth for mod downloading is not free.  Indeed, anyone who knows or prefers CKAN understands that Curse is VERY CKAN-unfriendly, as CKAN is based on metadata files that presume the ability to remote-call and remote-download hosted mods -- Curse actually updated their software to affirmatively prevent CKAN from doing it's thing, specifically to ensure that mod downloaders were forcibly exposed to Curse's banner ads.  This is why CKAN management favored a mod that was hosted on KerbalStuff, Github, or some other miscellaneous hosting (such as Dropbox / OneDrive / GDrive / etc.)

I am unfamiliar as to the exact particulars of Squad's licensing, but I'm fairly certain that Curse's deal is one of exclusivity -- that any other mod-hosting site is prevented by licensing restrictions from adopting any for-profit model that would compete with Curse.

My Proposal: With someone else's help, I can act as point man in forming a non-profit corporation of some kind (my own jurisdiction of New York would offer several filing options for this, and other jurisdictions may offer different options, each with advantages and disadvantages.)  I can even serve as a member of a corporation's managing board.  I suggest we find a way to manage and navigate the existing licensing restrictions, or possibly even negotiate with Squad in good faith to allow some form of compromise solution, that would allow SpaceDock or some KerbalStuff-successor to operate and generate modest revenue from hosting and CKAN integration, not for the purpose of generating lasting profits, but for the exclusive purpose of strengthening the non-profit product so that it remains as available and robust as the technology could allow.  From actually offsetting the digital costs of webhosting and bandwidth, I foresee the possibility to manage a small cohort of otherwise-volunteer programmers and other mod hobbyists by actually offering them some sort of financial incentive to donate their time.  I'm not suggesting we hire someone full time with salary and benefits, but something that would make their late nights of sacrificed personal time worthwhile.

I can be reached by PM here, or by email directly at David.Jacobson@brooklaw.edu.  I get a lot of emails from other sources, so to make yours stand out, please indicate "KerbalStuff Successor" in the subject line.  I am convinced that there can exist a fully-legal, fully-compliant, self-sustaining solution to this issue, and I'd care to be a significant contributor to that effort.

Best,
David

Do we have any thoughts on this kind of offer?

inigma

**Comment by inigma2** [comment]
I'm thinking if anything was done, it would have to be entirely pro bono (ie. free). If nothing decided now, then certainly it would be good to keep David as a standby contact should the need arise.

**Comment by godarklight** [comment]
There's a few problems with this message:

"KerbalStuff failed, ultimately, because of a poor incentive-model (cost of time and money) to update and maintain it." - SirCmpwn made it pretty clear that money wasn't an issue - and afaik he kinda just burnt out on looking after kerbalstuff, especially after some disagreements with other modders. Motivation is probably the biggest driving factor.

"SpaceDock, or any successor, will eventually run into the same problem in some form" - Perhaps, every dog has its day, but VITAS has been running the current server for other things for quite a long time now, SpaceDock appears right at home on it, and we don't have any plans for migration atm.

"CKAN understands that Curse is VERY CKAN-unfriendly" this is completely untrue now - CKAN has the goahead from jadedcat (a curse rep) to allow CKAN downloads from curse now. The reason they never tried before was because automated tools appeared to be against their terms of use - but jadedcat says otherwise.

"I can act as point man in forming a non-profit corporation of some kind" - I'm a bit sketchy about this. Currently we do have a patreon page which covers server costs, although I do realise that won't last forever. What exactly would the non-profit entail?

"I can even serve as a member of a corporation's managing board" - Now I'm really sketchy on this :P

"possibly even negotiate with Squad" for? Squad isn't going to pay modders unless they hire them to code for the game :P

I'm a bit sketchy about the whole thing, but I'll let others comment on it too. Currently doing what we are doing appears to be the best option to me.

**Comment by TN-1** [comment]
I agree with what @godarklight concluded.

**Comment by ghost** [comment]
I think we should not go overboard, we are hosting mods for a game with little cartoon like green men.
we are not even charging for use of the site, so any "Legal Advice" would be very simple stuff.

**Comment by jameswolff96** [comment]
Another important thing to realize is we are an alternative to, not a competitor with curse. 100% agree with @godarklight.

**Comment by ghost** [comment]
yeah i agree with @godarklight

**Comment by Shuudoushi** [comment]
@godarklight does have very good counter points, though having someone with at least legal experience kicking about could help first time modders in picking licenses and help encase of douchebaggery of CR/patent/TM trolls (even though that phase has luckily seemed to have died).

**Comment by godarklight** [comment]
@Shuudoushi That's more an issue for modders though than for us.

**Comment by jameswolff96** [comment]
While having someone like that around would be nice he seems like he has "big ideas" for the project and a lot of the stuff he is talking about seems like a conflict of interest for what the project is (at least in my opinion). It all depends on the type of person he is and if he would be able to, for lack of a better term, "tone it down".

**Comment by MisterFister2016** [comment]
Hi, I'm MisterFister from the forums.  Apparently my handle was already taken here...?  Anyway:

"I'm thinking if anything was done, it would have to be entirely pro bono (ie. free). ... then certainly it would be good to keep David as a standby contact should the need arise."  Absolutely pro bono (this is why I mentioned clinics, it's the term for law students practicing certain facets of law under the supervision of a licensed-attorney professor.)  I am in no way impatient here, but my idea (explained further below) would involve indicating that, in law, "an ounce of prevention" is a very accurate phrase.

"afaik he kinda just burnt out on looking after kerbalstuff, especially after some disagreements with other modders. Motivation is probably the biggest driving factor."  I entirely agree.  I was simply making the leap that motivation ultimately translates to funding at some point.  My understanding of SirCmpwn's statement on KS was that he was burning out as a result of doing all of this in his spare time.  My idea is low-key and wouldn't allow anyone to run a mod site in lieu of an actual "day job," but there's a psychological burnout-preventing motivator that comes with something small... perhaps the occasional Amazon giftcard or somesuch.  That said, I'm specifically suggesting that the financial COSTS of running SpaceDock shouldn't be something that would need to be fronted by the people who're also donating their time and expertise.  Through setting up something like a Patreon, or a PayPal Donate link, or even just an affiliate link to Amazon / Steam / G2A.com / anything else, I imagine that there'd be a way to get the operation to the point where it wouldn't cost someone BOTH their volunteered time AND their donated money from the same person.

"but jadedcat says otherwise."  I was unaware of this development.  I'll be curious to see how the community's mod-ecosystem evolves with this new info, of course.  It has the potential to render a lot of what I suggested moot or obsolete, but this isn't a guarantee.

"*I can act as point man in forming a non-profit corporation of some kind* - I'm a bit sketchy about this. Currently we do have a patreon page which covers server costs, although I do realise that won't last forever. What exactly would the non-profit entail? *I can even serve as a member of a corporation's managing board* - Now I'm really sketchy on this :P"  Heh.  I'm actually speaking in legalese-shorthand.  A non-profit, as I suggest it, would be a legal entity -- a company or corporation or something similar (lots of possible permutations on the specifics, hence my raising the idea early on) that would allow any "agreements" (funding, Patreon revenue, licensing agreements between the site and modders, or between Squad and the site, etc...) to be pointed and referenced from a single entity-point.  It would allow an opportunity to simplify the bird's nest of hodgepodge licensing agreements (such as modder-collaborated modifications to a mod -- for example FAR might carry ferram4's name, but lots of other people have contributed to it, each contributor with their own GPL 3.0 license rights and responsibilities... etc.) As for "member of a board," any "entity" needs a "person" to act as an agent.  Sometimes, with non-profit entities, it's difficult to find someone willing to stand in as a listed individual.  I was simply volunteering, IF that were an issue here.  Anyone else could do it, as well.

"*possibly even negotiate with Squad* for? Squad isn't going to pay modders unless they hire them to code for the game :P"  I actually didn't mean to imply that it would be a negotiation for payment, so much as negotiations for explicit sanctioned permission to operate with respect to licensing.  I'm not entirely sure I understand (due to my lack of technical expertise with respect to software design, website design, etc.) the exact intended scope, or the full extent of any POSSIBLE scope, of SpaceDock.  That said, I imagine that at some point, a certain feature or a certain capability might need to be hedged because it would infringe or butt up against a licensing restriction somewhere, and licensing restrictions ultimately radiate outward from Squad in one form or another.  If there were ever a need or a desire to actually email Squad and ask them for permission to make an exception for something that SpaceDock wanted to do (likely with the understanding that it not be to make a profit off of Squad's product, hence my non-profit-entity suggestion to begin with) then having something like my idea set up would allow for discussions like that to take days instead of months, simply because there'd be designated people in place on both ends to handle it.  It wouldn't create anything "official" with respect to how Squad advertises or markets their product, it would simply render "official" that SpaceDock itself would actually have a face and a person to talk to / hear from.

"I think we should not go overboard, we are hosting mods for a game with little cartoon like green men.
 we are not even charging for use of the site, so any "Legal Advice" would be very simple stuff."  This is entirely fine, I think, and given that I drew explicit attention to the fact that for the next few months I'm still a law student and therefore by definition won't be "experienced" as an attorney for a while, I would very much prefer that anything I would contribute would be slow and low-key just to ensure that I wouldn't screw anything up.  Beyond that, I'll just re-refer to the "ounce of prevention" idea I mentioned above.

"though having someone with at least legal experience kicking about could help first time modders in picking licenses and help encase of douchebaggery of CR/patent/TM trolls"  This, explicitly, is one major item that my proposal is designed to address.

And please don't assume I have "big ideas," in any bad sense of the phrase.  Simply, I'm an avid KSP player, I LOVE playing mod-heavy setups, and my lack of programming ability has prevented me from doing much to give back to this particular facet of the kommunity.  With the transition and / or upheaval currently unfolding, and the fact that even a year ago I would've been less capable to even offer what I'm suggesting now because it was a lot earlier in my course of studies here at law school, I think what you're reacting to -- correctly, I might add -- is my sheer enthusiasm with which I wanted to offer my support.  Please don't confuse the scope of my cheerleading with any scope of my ideas -- my ideas are intended to be small, low-key, "ounce of prevention" stuff, that would only scale upward in a specific circumstances that would pretty much have to involve someone else asking me to think bigger.

And yes, I'm foreseeing that I would not ask to be paid for this, and through clinics at my school, I can imagine not having to ask for money for any other assistance I might possibly need.  The only costs here would be government-imposed filing costs, which tend to be minimal.

**Comment by ethan3369** [comment]
I may not have any thing to contribute but my opinion but after the shutdown of KerbalStuff I don't want that to have ever again. I think that some amount of legal protection would help in ensuring that SpaceDock stays around forever.

**Comment by inigma2** [comment]
I am closing this issue for now. We have the information on file, but at this time we've decided to not pursue this. Thank you!
